class VectorStoreException(Exception): ...

class VectorStoreAuthError(VectorStoreException): ...

class VectorStoreNotFoundError(VectorStoreException): ...

class VectorStorePermissionError(VectorStoreException): ...

class VectorStoreServiceError(VectorStoreException): ...

class VectorStoreInternalError(VectorStoreException): ...

class VectorStoreNotImplementedError(VectorStoreException): ...

class VectorStoreIndexAlreadyExist(VectorStoreException): ...